receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
  resource:
    attributes:
      - key: service.namespace
        value: otel-example
        action: upsert

exporters:
  awsxray:
    region: us-east-1

  awsemf:
    namespace: OtelFargate
    log_group_name: "/ecs/otel-logs"
    log_stream_name: "otel-metrics"
    region: us-east-1

  awscloudwatchlogs:
    log_group_name: "/otel/collector/logs"
    log_stream_name: "otel-log-stream"
    region: us-east-1

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure_skip_verify: true
    default_labels_enabled:
      service.name: true
      service.namespace: true
      severity: true

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [awsxray, otlp/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [awsemf, debug]

    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [awscloudwatchlogs, loki, debug]
