receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
    timeout: 5s

exporters:
  awsxray:
    region: us-east-1
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]
